# Generated by Django 5.2.6 on 2025-09-04 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'start_date'], name='events_even_city_id_bea4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'start_date'], name='events_even_categor_ed450e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'start_date'], name='events_even_is_acti_a2b5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'end_date'], name='events_even_start_d_7e0d92_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['external_source', 'external_id'], name='events_even_externa_ec3227_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='end_date_after_start_date'),
        ),
    ]
